# Generated by Django 3.0.11 on 2021-01-14 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='author/'),
            preserve_default=False,
        ),
    ]
